# Generated by Django 2.2.6 on 2019-11-10 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0002_messages_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskCode', models.CharField(max_length=10)),
                ('taskHeading', models.CharField(max_length=200)),
                ('taskContent', models.TextField()),
                ('lastDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('taskScore', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tasks',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.AlterField(
            model_name='messages',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='fname',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='ip',
            field=models.CharField(max_length=50, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='lname',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Name', max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('phoneNumber', models.IntegerField(blank=True, default='5412781925', verbose_name='Phone Number')),
                ('score', models.IntegerField(blank=True, default=0, verbose_name='Score')),
                ('year', models.CharField(choices=[('I Year', 'I Year'), ('II Year', 'II Year')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
