# Generated by Django 2.2.6 on 2019-11-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20191110_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
