# Generated by Django 2.2.6 on 2019-11-10 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Name', max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('phoneNumber', models.IntegerField(blank=True, default='5412781925', verbose_name='Phone Number')),
                ('score', models.IntegerField(blank=True, default=0, verbose_name='Score')),
                ('year', models.CharField(choices=[('I Year', 'I Year'), ('II Year', 'II Year')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
