# Generated by Django 2.2.6 on 2019-11-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workLink',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link of Portfolio'),
        ),
    ]
