# Generated by Django 2.2.6 on 2019-11-14 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_profile_worklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
