# Generated by Django 2.2.6 on 2019-11-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskCode',
            field=models.CharField(max_length=50),
        ),
    ]
