# Generated by Django 2.2.6 on 2019-11-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_auto_20191114_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'AR VR Groups',
                'verbose_name_plural': 'AR VR Groups',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='groupAssociated',
            field=models.ManyToManyField(to='Core.GroupAR'),
        ),
    ]
