# Generated by Django 2.2.6 on 2019-11-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_auto_20191114_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupar',
            name='groupName',
            field=models.CharField(max_length=100),
        ),
    ]
