# Generated by Django 2.2.6 on 2019-11-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_auto_20191114_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ManyToManyField(to='Core.GroupAR'),
        ),
    ]
