# Generated by Django 2.2.6 on 2019-11-14 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0013_taskstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetCode', models.CharField(max_length=50)),
                ('meetHeading', models.CharField(max_length=100)),
                ('meetPurpose', models.TextField()),
                ('meetAttendance', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('meetGroup', models.ManyToManyField(to='Core.GroupAR')),
            ],
            options={
                'verbose_name': 'Meetings',
                'verbose_name_plural': 'Meetings',
            },
        ),
    ]
