# Generated by Django 2.2.6 on 2019-11-14 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='meetDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meetings',
            name='meetVenue',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
