# Generated by Django 2.2.6 on 2019-11-14 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_auto_20191114_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='excuse',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='experience',
        ),
        migrations.AlterField(
            model_name='meetings',
            name='meetCode',
            field=models.CharField(max_length=50, verbose_name='Meeting Code'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='meetDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='meetHeading',
            field=models.CharField(max_length=100, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='meetPurpose',
            field=models.TextField(verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='meetVenue',
            field=models.CharField(max_length=100, verbose_name='Venue'),
        ),
    ]
