# Generated by Django 2.2.6 on 2019-11-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_auto_20191114_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
